### ISSUE TITLE
Can't install this via Bower

### ISSUE THREAD

**Issue by paulxtiseo** [joshuapekera/animate#6]
Trying to install it on my MacBook and get this error:

```
$ bower install animate
bower not-cached    git://github.com/joshuapekera/animate.git#*
bower resolve       git://github.com/joshuapekera/animate.git#*
bower download      https://github.com/joshuapekera/animate/archive/1.0.1.tar.gz
bower extract       animate#* archive.tar.gz
bower EMALFORMED    Failed to read /var/folders/gh/vzfh5kgj71j0_nl2vf34jrcny3gxt0/T/user/bower/animate-9969-IAegSd/bower.json
```

**Comment by paulxtiseo** [comment]
I believe the issue may be that the 1.0.1.tar.gz archive/package has a malformed JSON. There's a trailing comma in the devDependencies item.

**Comment by paulxtiseo** [comment]
FWIW, was able to install via `bower install https://github.com/joshuapekera/animate.git#master`.

**Comment by joshuapekera** [comment]
I have neglected this repo for a while. I'll be making some changes soon to bring this up-to-date.

**Comment by mauromangas** [comment]
Same here!

**Comment by jakehockey10** [comment]
In case any more information helps gets this solved:

```shell
jake@jake-pc:~/Projects/angularjs/practice/api-app$ bower install --save animate --verbose
bower animate#*             not-cached https://github.com/joshuapekera/animate.git#*
bower animate#*                resolve https://github.com/joshuapekera/animate.git#*
bower animate#*               checkout 1.0.1
bower animate#*             EMALFORMED Failed to read /tmp/jake/bower/a2a424217f809672e8fe80ddeab36781-10875-yqxR3n/bower.json

Additional error details:
Unexpected token }

Stack trace:
SyntaxError: Unexpected token }
    at Object.parse (native)
    at /home/jake/.node/lib/node_modules/bower/lib/node_modules/bower-json/lib/json.js:42:29
    at /home/jake/.node/lib/node_modules/bower/lib/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
From previous event:
    at readJson (/home/jake/.node/lib/node_modules/bower/lib/util/readJson.js:17:6)
    at GitHubResolver.Resolver._readJson (/home/jake/.node/lib/node_modules/bower/lib/core/resolvers/Resolver.js:180:12)

Console trace:
Error
    at StandardRenderer.error (/home/jake/.node/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/home/jake/.node/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (/home/jake/.node/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /home/jake/.node/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/home/jake/.node/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /home/jake/.node/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/home/jake/.node/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/jake/.node/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 5.10.1
OS: Linux 4.4.0-21-generic x64
jake@jake-pc:~/Projects/angularjs/practice/api-app$
```

**Comment by jakehockey10** [comment]
@paulxtiseo , this is the case for me as well.

**Comment by sir-gon** [comment]
Same case here
